Adding Bio and Socials
Rishit-dagli/pod-3.1.2-portfolio pull request #18
Opened 2021-07-22 13:57 UTC by harshgeek4coder

## Bio and Social Links

- Adding Bio in About Me Section
- Adding Social Links in Footer Section

2021-07-22 14:14 UTC, Rishit-dagli requested changes

2021-07-22 14:14 UTC, Rishit-dagli commented on _config.yml
> +
extra lines

2021-07-22 14:14 UTC, Rishit-dagli commented on Gemfile
> +
extra lines

2021-07-22 14:14 UTC, Rishit-dagli commented on _data/about.yml
> +
extra lines

2021-07-22 14:14 UTC, Rishit-dagli commented on _data/education.yml
> +
Why is this file changed?

2021-07-22 14:14 UTC, Rishit-dagli commented on _data/socials.yml
> +  link: 'https://twitter.com/MLHacks?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor'
Let's reference this from `_config.yml`?

2021-07-22 14:14 UTC, Rishit-dagli commented on _data/socials.yml
> +  link: 'https://github.com/MLH-Fellowship'
Let's reference this too from `_config.yml`?

2021-07-22 14:14 UTC, Rishit-dagli commented on _data/socials.yml
> +  link: 'https://www.linkedin.com/school/mlh-fellowship/'
Sam here. Let's reference this too from `_config.yml`?

2021-07-23 05:41 UTC, harshgeek4coder commented on _data/education.yml
> +
Had some custom tweaks, removed extra lines though

2021-07-23 05:42 UTC, harshgeek4coder commented on _data/socials.yml
> +  link: 'https://twitter.com/MLHacks?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor'
we can, but i followed same convention -> YML files and HTML templates to remain same, if required in future to add extra elements

2021-07-23 05:42 UTC, harshgeek4coder commented on _data/about.yml
> +
Done

2021-07-23 05:43 UTC, harshgeek4coder commented on Gemfile
> +
Done

2021-07-23 05:43 UTC, harshgeek4coder commented on _config.yml
> +
Done

2021-07-23 05:48 UTC, harshgeek4coder commented
committed the requested changes

2021-07-23 09:54 UTC, shreyaparadkar requested changes

2021-07-23 09:54 UTC, shreyaparadkar commented on assets/css/main.scss
> +
extra lines

2021-07-23 14:23 UTC, Rishit-dagli approved these changes
Thanks @harshgeek4coder 👍

2021-07-23 17:47 UTC, shreyaparadkar approved these changes

2021-07-24 18:26 UTC, ayushmaang commented
LGTM. Like the fact that everyone approves beforehand.

2021-07-24 18:26 UTC, merged